services:
  postgres:
    image: postgres:16-alpine
    container_name: ss_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ss_postgres_data:/var/lib/postgresql/data
      - ./bd:/docker-entrypoint-initdb.d:ro
    networks:
      - ss_net

  backend:
    image: leandropereiran/ss_backend:latest
    container_name: ss_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      FASTIFY_PORT: ${FASTIFY_PORT}
      FASTIFY_HOST: ${FASTIFY_HOST}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - ss_net

  frontend:
    image: leandropereiran/ss_frontend:latest
    container_name: ss_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - ss_net

  nginx:
    image: nginx:1.27-alpine
    container_name: ss_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - ss_net

  certbot:
    image: certbot/certbot:latest
    container_name: ss_certbot
    command: >
      certbot certonly --webroot
      -w /var/www/certbot
      --agree-tos
      --register-unsafely-without-email
      -d grupo02.brazilsouth.cloudapp.azure.com
    volumes:
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - ss_net

volumes:
  ss_postgres_data:

networks:
  ss_net:
    driver: bridge
